language: java

jdk:
  - oraclejdk8

script: mvn clean test

before_script:
  - pip install --user codecov

after_success:
  - codecov

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3007ff19b5fc6a992999
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
